### ISSUE TITLE
Model checkpoints on Hugging Face

### ISSUE THREAD

**Issue by katielink** [DeepGraphLearning/ProtST#2]
Hey there! Awesome work with ProtST! It would be great to have the model checkpoints on the [Hugging Face Hub](https://huggingface.co/). Here are the docs for how to upload them: https://huggingface.co/docs/hub/models-uploading. Let me know if I can help with that!

**Comment by KatarinaYuan** [comment]
Hi, thank you for your interest in our work. A huggingface hub for ProtST (https://huggingface.co/katarinayuan/ProtST/tree/main/pretrained_ckpt) has been created to store the pretraining model checkpoints as suggested. Please let us know if there are further questions.
