### ISSUE TITLE
How to get pre-training data?

### ISSUE THREAD

**Issue by Greay83** [DeepGraphLearning/ProtST#3]
Hi, this is a great work. I notice that this repositories does not contain the corpus used in pre-training, called " ProtDescribe". Can you provide it? Thanks so much.

**Comment by KatarinaYuan** [comment]
Hi, thank you for your interest in our work! `ProtDescribe` is implemented as class `UniProtSeqText` in file `./protst/dataset.py`. I also have updated the url link to download the `TrEmbl` version of `ProtDescribe`. Please let us know if you have further questions.

**Comment by Greay83** [comment]
No problem for now. Thanks so much again.
